---
galaxy_info:
  author: jeqo (quilcate.jorge@gmail.com)
  description: java role to install and configure java from different providers (oracle, openjdk, azul) in linux distributions (el and ubuntu).
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
  - development
dependencies: []
