---
#

- debug:
    var: ansible_os_family

- fail: message="jre is not valid with zulu provider"
  when: java_type == "jre"

- include: install-azul-zulu-debian.yml
  when: ansible_os_family == "Debian"

- include: install-azul-zulu-redhat.yml
  when: ansible_os_family == "RedHat"
